version: '3.8'

services:
  ratelimiter:
    build: ./ratelimiter_proxy
    ports:
      - "12227:12227"
    networks:
      - app-network

  tracker:
    build: ./tracker
    volumes:
      - ./data:/usr/src/app/data
    depends_on:
      - ratelimiter
    networks:
      - app-network
    env_file:
      - .env
    environment:
      - RATELIMITER_HOST=ratelimiter
      - RATELIMITER_PORT=12227

  api:
    build: ./api
    volumes:
      - ./data:/usr/src/app/data
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - api
    environment:
      - API_HOST=api
      - API_PORT=8000

networks:
  app-network:
    driver: bridge
    networks:
      - app-network
