version: '3.8'

services:
  default_database:
    restart: unless-stopped
    image: mongo:latest
    env_file:
      - ./backend/.env
    ports:
      - "27017:27017"
    volumes:
      - default_database_data:/data/db
    networks:
      - app-network

  backend:
    build: ./backend
    depends_on:
      - default_database
      - ratelimiter
    networks:
      - app-network
    env_file:
      - ./backend/.env
    ports:
      - "8001:8000"
    environment:
      - DEFAULT_DATABASE_HOSTNAME=default_database
      - RATELIMITER_HOST=ratelimiter
      - RATELIMITER_PORT=12227

  ratelimiter:
    build: ./ratelimiter_proxy
    ports:
      - "12227:12227"
    networks:
      - app-network

  tracker:
    build: ./tracker
    volumes:
      - ./data:/usr/src/app/data
    depends_on:
      - ratelimiter
    networks:
      - app-network
    env_file:
      - .env
    environment:
      - RATELIMITER_HOST=ratelimiter
      - RATELIMITER_PORT=12227

  api:
    build: ./api
    volumes:
      - ./data:/usr/src/app/data
    depends_on:
      - ratelimiter
    networks:
      - app-network
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - RATELIMITER_HOST=ratelimiter
      - RATELIMITER_PORT=12227

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - api
    environment:
      - API_HOST=api
      - API_PORT=8000

networks:
  app-network:
    driver: bridge

volumes:
  default_database_data:
